//! SeaORM Entity. Generated by sea-orm-codegen 0.4.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "forums")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub label: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub last_post_id: Option<i32>,
    pub last_thread_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rules: Option<String>,
    pub parent_id: Option<i32>,
    pub display_order: i32,
    /// Default icon/emoji for the forum
    pub icon: String,
    /// Icon shown when forum has unread content
    pub icon_new: String,
    /// Custom image/SVG for default forum icon
    pub icon_attachment_id: Option<i32>,
    /// Custom image/SVG for forum icon when new content exists
    pub icon_new_attachment_id: Option<i32>,
    /// Whether tags are enabled for threads in this forum
    pub tags_enabled: bool,
    /// If true, only existing/admin-created tags can be used (no ad-hoc tags)
    pub restrict_tags: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::posts::Entity",
        from = "Column::LastPostId",
        to = "super::posts::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    LastPost,
    #[sea_orm(
        belongs_to = "super::threads::Entity",
        from = "Column::LastThreadId",
        to = "super::threads::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Threads,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Parent,
    #[sea_orm(
        belongs_to = "super::attachments::Entity",
        from = "Column::IconAttachmentId",
        to = "super::attachments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IconAttachment,
    #[sea_orm(
        belongs_to = "super::attachments::Entity",
        from = "Column::IconNewAttachmentId",
        to = "super::attachments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IconNewAttachment,
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LastPost.def()
    }
}

impl Related<super::threads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Threads.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
